# fly.toml app configuration file generated for social-server-eoin-1 on 2024-07-25T17:22:31-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "social-server-eoin-1"
primary_region = "ord"
console_command = "/code/manage.py shell"

[build]

[env]
  PORT = "8000"
  ENVIRONMENT = "production"  # Ensure this is set for production

[[mounts]]
  source = "database_volume"
  destination = "/mnt/volume_mount"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[[statics]]
  guest_path = "/mnt/volume_mount/media"
  url_prefix = "/media/"
