# Generated by Django 5.0.6 on 2024-06-04 13:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0003_image_created_at_alter_image_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpost',
            old_name='attached_image',
            new_name='image',
        ),
        migrations.AddField(
            model_name='userpost',
            name='no_of_like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
