# Generated by Django 5.0.6 on 2024-06-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0004_rename_attached_image_userpost_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
