# Generated by Django 5.0.6 on 2024-07-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0009_alter_userpost_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
